# Generated by Django 4.1.7 on 2023-03-05 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('snip_id', models.AutoField(primary_key=True, serialize=False)),
                ('snippet', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('created_user_id', models.TextField()),
                ('title', models.TextField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='webapp.tag')),
            ],
            options={
                'ordering': ['time_stamp'],
            },
        ),
    ]
